import { Router } from 'express';
import { AuthController } from '../controllers/AuthController.js';
import { ApiKeyController } from '../controllers/ApiKeyController.js';
import { ScanController } from '../controllers/ScanController.js';
import { UserController } from '../controllers/UserController.js';
import { AuthService } from '../services/authService.js';
import { ApiKeyService } from '../services/apiKeyService.js';
import { ScanService } from '../services/scanService.js';
import { UserService } from '../services/userService.js';
import { UserRepository } from '../repositories/UserRepository.js';
import { ApiKeyRepository } from '../repositories/ApiKeyRepository.js';
import { ScanRepository } from '../repositories/ScanRepository.js';
import { authenticate, authorize } from '../middleware/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { validate } from '../middleware/validate.js';
import { createApiKeySchema, createUserSchema, ingestSchema, loginSchema, profileSchema } from '../validators/schemas.js';

const users = new UserRepository(); const keys = new ApiKeyService(new ApiKeyRepository()); const scans = new ScanService(new ScanRepository());
const auth = new AuthController(new AuthService(users)); const apiKeys = new ApiKeyController(keys); const scan = new ScanController(scans, keys); const user = new UserController(new UserService(users));
export const router = Router();
router.post('/auth/login', validate(loginSchema), asyncHandler(auth.login));
router.get('/auth/me', authenticate, asyncHandler(auth.me));
router.patch('/auth/me', authenticate, validate(profileSchema), asyncHandler(auth.updateProfile));
router.get('/api-keys', authenticate, asyncHandler(apiKeys.list));
router.post('/api-keys', authenticate, validate(createApiKeySchema), asyncHandler(apiKeys.create));
router.delete('/api-keys/:id', authenticate, asyncHandler(apiKeys.revoke));
router.post('/ingest', validate(ingestSchema), asyncHandler(scan.ingestApi));
router.post('/scans', authenticate, validate(ingestSchema), asyncHandler(scan.ingest));
router.get('/scans', authenticate, asyncHandler(scan.list));
router.get('/scans/:id', authenticate, asyncHandler(scan.get));
router.get('/dashboard/overview', authenticate, asyncHandler(scan.overview));
router.get('/dashboard/pipelines', authenticate, asyncHandler(scan.pipelines));
router.get('/users', authenticate, authorize('admin'), asyncHandler(user.list));
router.post('/users', authenticate, authorize('admin'), validate(createUserSchema), asyncHandler(user.create));
