import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, setToken, type ApiKey, type Scan, type User } from './api';

type Page = 'dashboard' | 'scans' | 'upload' | 'keys' | 'users' | 'profile';
type IconName = 'dashboard' | 'policy' | 'upload_file' | 'key' | 'group' | 'person' | 'logout' | 'login' | 'visibility' | 'content_copy' | 'delete' | 'add' | 'save' | 'cloud_upload' | 'refresh' | 'schedule';
const severityClass = (severity: string) => `severity ${severity.toLowerCase()}`;
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString() : 'Never';
const ErrorBox = ({ error }: { error: unknown }) => error ? <p className="error">{error instanceof Error ? error.message : 'Request failed'}</p> : null;
const Icon = ({ name }: { name: IconName }) => <span className="material-symbols-outlined" aria-hidden="true">{name}</span>;

function Login({ onLoggedIn }: { onLoggedIn: (user: User) => void }) {
  const [email, setEmail] = useState('admin@security.local'); const [password, setPassword] = useState('ChangeMe123!');
  const login = useMutation({ mutationFn: () => api.login(email, password), onSuccess: ({ token, user }) => { setToken(token); onLoggedIn(user); } });
  const submit = (event: FormEvent) => { event.preventDefault(); login.mutate(); };
  return <main className="login-shell"><section className="login-card glass"><div className="brand-mark">S</div><p className="eyebrow">SECURITY INTELLIGENCE</p><h1>Sentinel Reports</h1><p className="muted">Centralized evidence for every pipeline, scanner, and security decision.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label><ErrorBox error={login.error} /><button disabled={login.isPending}><Icon name="login" />{login.isPending ? 'Signing in...' : 'Sign in'}</button></form><p className="hint">Local initialization credentials are prefilled for first-run use.</p></section></main>;
}
function SummaryCards({ summary }: { summary: { scans?: number; critical?: number; high?: number; medium?: number; low?: number; totalFindings?: number } }) {
  const values = [['Scans', summary.scans ?? 0, 'neutral'], ['Critical', summary.critical ?? 0, 'critical'], ['High', summary.high ?? 0, 'high'], ['Medium', summary.medium ?? 0, 'medium'], ['Findings', summary.totalFindings ?? 0, 'neutral']];
  return <div className="summary-grid">{values.map(([label, value, tone]) => <article className={`metric glass ${tone}`} key={label as string}><span>{label}</span><strong>{value}</strong></article>)}</div>;
}
function Dashboard({ onOpenScan }: { onOpenScan: (scan: Scan) => void }) {
  const overview = useQuery({ queryKey: ['overview'], queryFn: api.overview }); const pipelines = useQuery({ queryKey: ['pipelines'], queryFn: api.pipelines }); const scans = useQuery({ queryKey: ['scans'], queryFn: api.scans });
  return <section><div className="page-title"><div><p className="eyebrow">LIVE SECURITY POSTURE</p><h2>Executive overview</h2></div><span className="live"><i /><Icon name="refresh" />Updated every 30 seconds</span></div><SummaryCards summary={overview.data ?? {}} /><ErrorBox error={overview.error || pipelines.error || scans.error} /><div className="dashboard-grid"><section className="glass panel"><h3>Jenkins pipelines</h3><div className="pipeline-list">{(pipelines.data ?? []).map((pipeline) => <article key={pipeline._id} className="pipeline"><div><strong>{pipeline._id}</strong><span>{pipeline.scans} scans · last scan {formatDate(pipeline.latestScan)}</span></div><div className="pipeline-counts"><b className="critical">{pipeline.critical} critical</b><b className="high">{pipeline.high} high</b></div></article>)}{!pipelines.isLoading && !pipelines.data?.length && <Empty text="No reports have been ingested yet." />}</div></section><section className="glass panel"><h3>Latest reports</h3><div className="compact-list">{(scans.data ?? []).slice(0, 6).map((scan) => <button className="scan-row" onClick={() => onOpenScan(scan)} key={scan._id}><span className="tool-label">{scan.tool}</span><span><strong>{scan.pipeline}</strong><small>{scan.artifact || scan.branch || 'No artifact declared'}</small></span><b>{scan.summary.total}</b><Icon name="visibility" /></button>)}{!scans.isLoading && !scans.data?.length && <Empty text="Upload a report to populate this dashboard." />}</div></section></div></section>;
}
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p>; }
function Scans({ selected, onOpen }: { selected: Scan | null; onOpen: (scan: Scan) => void }) {
  const scans = useQuery({ queryKey: ['scans'], queryFn: api.scans });
  return <section><div className="page-title"><div><p className="eyebrow">REPORT INVENTORY</p><h2>Security scans</h2></div><span className="muted">Newest 200 reports</span></div><ErrorBox error={scans.error} /><div className="glass table-wrap"><table><thead><tr><th>Pipeline</th><th>Tool</th><th>Artifact / branch</th><th>Risk</th><th>Scanned</th><th /></tr></thead><tbody>{(scans.data ?? []).map((scan) => <tr key={scan._id}><td><strong>{scan.pipeline}</strong><small>{scan.buildNumber && `Build ${scan.buildNumber}`}</small></td><td><span className="tool-label">{scan.tool}</span></td><td>{scan.artifact || scan.branch || '—'}</td><td><span className={severityClass(scan.summary.critical ? 'critical' : scan.summary.high ? 'high' : 'low')}>{scan.summary.critical} critical · {scan.summary.high} high</span></td><td>{formatDate(scan.scannedAt)}</td><td><button className="text-button" onClick={() => onOpen(scan)}><Icon name="visibility" />Inspect</button></td></tr>)}</tbody></table>{!scans.isLoading && !scans.data?.length && <Empty text="No scan reports are available." />}</div>{selected && <ScanDetail scan={selected} />}</section>;
}
function ScanDetail({ scan }: { scan: Scan }) { return <section className="glass panel scan-detail"><div className="page-title"><div><p className="eyebrow">{scan.tool.toUpperCase()} REPORT</p><h3>{scan.pipeline}</h3></div><span>{formatDate(scan.scannedAt)}</span></div><SummaryCards summary={scan.summary} /><div className="findings">{scan.findings.map((finding, index) => <article className="finding" key={`${finding.identifier}-${index}`}><span className={severityClass(finding.severity)}>{finding.severity}</span><div><strong>{finding.title}</strong><small>{finding.identifier} · {finding.location || finding.target || 'Location unavailable'}</small><p>{finding.description}</p>{finding.reference && <a href={finding.reference} target="_blank" rel="noreferrer">Reference</a>}</div></article>)}{!scan.findings.length && <Empty text="This report contains no findings." />}</div></section>; }
function Upload() {
  const client = useQueryClient(); const [pipeline, setPipeline] = useState(''); const [tool, setTool] = useState<'trivy' | 'semgrep'>('trivy'); const [report, setReport] = useState(''); const [metadata, setMetadata] = useState({ buildNumber: '', branch: '', commit: '', buildUrl: '' });
  const upload = useMutation({ mutationFn: () => api.upload({ pipeline, tool, report: JSON.parse(report), ...Object.fromEntries(Object.entries(metadata).filter(([, value]) => value.trim())), }), onSuccess: () => { setReport(''); client.invalidateQueries({ queryKey: ['scans'] }); client.invalidateQueries({ queryKey: ['overview'] }); client.invalidateQueries({ queryKey: ['pipelines'] }); } });
  const chooseFile = async (file?: File) => { if (!file) return; setReport(await file.text()); };
  return <section><div className="page-title"><div><p className="eyebrow">MANUAL INGESTION</p><h2>Upload a scan output</h2></div></div><form className="glass panel form-grid" onSubmit={(e) => { e.preventDefault(); upload.mutate(); }}><label>Jenkins pipeline<input value={pipeline} onChange={(e) => setPipeline(e.target.value)} placeholder="payments-service" required /></label><label>Scanner<select value={tool} onChange={(e) => setTool(e.target.value as 'trivy' | 'semgrep')}><option value="trivy">Trivy</option><option value="semgrep">Semgrep</option></select></label><label>Build number<input value={metadata.buildNumber} onChange={(e) => setMetadata({ ...metadata, buildNumber: e.target.value })} /></label><label>Branch<input value={metadata.branch} onChange={(e) => setMetadata({ ...metadata, branch: e.target.value })} /></label><label>Commit SHA<input value={metadata.commit} onChange={(e) => setMetadata({ ...metadata, commit: e.target.value })} /></label><label>Build URL<input type="url" value={metadata.buildUrl} onChange={(e) => setMetadata({ ...metadata, buildUrl: e.target.value })} /></label><label className="full">Report JSON<input type="file" accept="application/json,.json" onChange={(e) => chooseFile(e.target.files?.[0])} required /></label>{report && <pre className="json-preview">{report.slice(0, 900)}{report.length > 900 ? '\n…' : ''}</pre>}<ErrorBox error={upload.error} /><button disabled={upload.isPending}><Icon name="cloud_upload" />{upload.isPending ? 'Validating report...' : 'Upload and parse report'}</button></form></section>;
}
function ApiKeys() {
  const client = useQueryClient(); const keys = useQuery({ queryKey: ['keys'], queryFn: api.keys }); const [label, setLabel] = useState(''); const [expiry, setExpiry] = useState(''); const [revealed, setRevealed] = useState<string | null>(null);
  const create = useMutation({ mutationFn: () => api.createKey({ label, expiresAt: expiry ? new Date(expiry).toISOString() : null }), onSuccess: (value) => { setRevealed(value.key); setLabel(''); setExpiry(''); client.invalidateQueries({ queryKey: ['keys'] }); } });
  const revoke = useMutation({ mutationFn: api.revokeKey, onSuccess: () => client.invalidateQueries({ queryKey: ['keys'] }) });
  return <section><div className="page-title"><div><p className="eyebrow">PIPELINE CREDENTIALS</p><h2>API keys</h2></div></div><div className="two-column"><form className="glass panel" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><h3>Create an ingestion key</h3><p className="muted">The complete key is displayed once. It is stored only as a secure hash.</p><label>Key label<input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Production Jenkins" required /></label><label>Expiry date <span className="muted">(optional)</span><input type="datetime-local" value={expiry} onChange={(e) => setExpiry(e.target.value)} /></label><ErrorBox error={create.error} /><button disabled={create.isPending}><Icon name="key" />Generate key</button>{revealed && <div className="secret"><strong>Copy this key now</strong><code>{revealed}</code><button type="button" className="secondary" onClick={() => navigator.clipboard.writeText(revealed)}><Icon name="content_copy" />Copy key</button></div>}</form><section className="glass panel"><h3>Active key registry</h3><ErrorBox error={keys.error} />{(keys.data ?? []).map((key: ApiKey) => <article className="key-row" key={key._id}><div><strong>{key.label}</strong><code>{key.prefix}...</code><small>Expires: {key.expiresAt ? formatDate(key.expiresAt) : 'Never'} · Last used: {formatDate(key.lastUsedAt)}</small></div>{key.revokedAt ? <span className="muted">Revoked</span> : <button className="danger-button" onClick={() => revoke.mutate(key._id)}><Icon name="delete" />Revoke</button>}</article>)}{!keys.isLoading && !keys.data?.length && <Empty text="No API keys have been created." />}</section></div></section>;
}
function Users() {
  const client = useQueryClient(); const users = useQuery({ queryKey: ['users'], queryFn: api.users }); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'user' });
  const create = useMutation({ mutationFn: () => api.createUser(form), onSuccess: () => { setForm({ name: '', email: '', password: '', role: 'user' }); client.invalidateQueries({ queryKey: ['users'] }); } });
  return <section><div className="page-title"><div><p className="eyebrow">ACCESS CONTROL</p><h2>User management</h2></div></div><div className="two-column"><form className="glass panel" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><h3>Create platform user</h3><label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><label>Initial password<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} minLength={12} required /></label><label>Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="user">Normal user</option><option value="admin">Administrator</option></select></label><p className="hint">Passwords need 12+ characters with uppercase, lowercase, and a number.</p><ErrorBox error={create.error} /><button disabled={create.isPending}><Icon name="add" />Create user</button></form><section className="glass panel"><h3>Users</h3><div className="user-list">{(users.data ?? []).map((item) => <article className="key-row" key={item.id || item._id}><div><strong>{item.name}</strong><small>{item.email}</small></div><span className={`role ${item.role}`}>{item.role}</span></article>)}{!users.isLoading && !users.data?.length && <Empty text="No user records are available." />}</div></section></div></section>;
}
function Profile({ user, onChange }: { user: User; onChange: (value: User) => void }) {
  const [form, setForm] = useState({ name: user.name, email: user.email, currentPassword: '', newPassword: '' }); const update = useMutation({ mutationFn: () => api.profile(Object.fromEntries(Object.entries(form).filter(([, value]) => value))), onSuccess: onChange });
  return <section><div className="page-title"><div><p className="eyebrow">ACCOUNT SETTINGS</p><h2>Your profile</h2></div></div><form className="glass panel profile-form" onSubmit={(e) => { e.preventDefault(); update.mutate(); }}><label>Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label>Email address<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><hr /><p className="muted">Leave password fields blank to keep your current password.</p><label>Current password<input type="password" value={form.currentPassword} onChange={(e) => setForm({ ...form, currentPassword: e.target.value })} /></label><label>New password<input type="password" value={form.newPassword} onChange={(e) => setForm({ ...form, newPassword: e.target.value })} minLength={12} /></label><ErrorBox error={update.error} /><button disabled={update.isPending}><Icon name="save" />Save changes</button></form></section>;
}
function App() {
  const [user, setUser] = useState<User | null>(null); const [page, setPage] = useState<Page>('dashboard'); const [selected, setSelected] = useState<Scan | null>(null);
  const client = useQueryClient();
  const session = useQuery({ queryKey: ['me'], queryFn: api.me, enabled: Boolean(localStorage.getItem('sentinel_token')), retry: false });
  const activeUser = user ?? session.data;
  if (!activeUser) return <Login onLoggedIn={setUser} />;
  const navigation: Array<[Page, string, IconName]> = [['dashboard', 'Overview', 'dashboard'], ['scans', 'Scans', 'policy'], ['upload', 'Upload', 'upload_file'], ['keys', 'API keys', 'key'], ['profile', 'Profile', 'person'], ...(activeUser.role === 'admin' ? [['users', 'Users', 'group'] as [Page, string, IconName]] : [])];
  const openScan = (scan: Scan) => { setSelected(scan); setPage('scans'); };
  const signOut = () => { setToken(''); client.removeQueries(); setSelected(null); setPage('dashboard'); setUser(null); };
  return <div className="app-shell"><aside className="sidebar"><div className="logo"><span className="brand-mark">S</span><span>Sentinel<span>Reports</span></span></div><nav>{navigation.map(([target, label, icon]) => <button className={page === target ? 'active' : ''} onClick={() => setPage(target)} key={target}><Icon name={icon} /><span>{label}</span></button>)}</nav><div className="account"><strong>{activeUser.name}</strong><small>{activeUser.role === 'admin' ? 'Administrator' : 'Normal user'}</small><button onClick={signOut}><Icon name="logout" /><span>Sign out</span></button></div></aside><main className="content">{page === 'dashboard' && <Dashboard onOpenScan={openScan} />}{page === 'scans' && <Scans selected={selected} onOpen={openScan} />}{page === 'upload' && <Upload />}{page === 'keys' && <ApiKeys />}{page === 'users' && activeUser.role === 'admin' && <Users />}{page === 'profile' && <Profile user={activeUser} onChange={setUser} />}</main></div>;
}
export default App;
